package-lock.json
package.json
src/App.tsx
src/components/NavBar.tsx
src/main.tsx
src/pages/MISignupFormPage.tsx
src/pages/SignInSignUpPage.tsx
src/pages/SignUpFormPage.tsx
src/pages/UpdateAccountPage.tsx
src/pages/ViewPairsPage.tsx

No longer am I using a switch case for routing!

Browser router migration

---

.github/workflows/drybuild.yaml
cspell.json
package.json
src/components/TimeRangeSelector/InterviewAvailabilitySelector2D.tsx

Author: Shawn
Added dryrun build when creating a PR, also fixed more of Elijahs spelling mistakes 😉 
So we know builds are good before merging.

Add dryrun build to PRs

---

src/services/api.ts

Author:  Shawn
Adds the server ip.

Add server url

---

package.json

Fix URL typo

---

vite.config.ts

Author: Shawn
Updates the vite.config

Remove base of domain

---

src/components/ProtectedRoute.tsx
src/components/utils/RandomUtils.tsx

Author: Elijah
Fixed infinite loading by removing if check in protected route

fixed loading

---

src/components/MemberProfileEdit.tsx
src/components/MemberProfileView.tsx
src/pages/DirectoryPage.tsx
src/pages/MemberProfilePage.tsx
src/services/member.ts

Author: Elijah
Fixed profile view and update

profile pages

---

cspell.json
package-lock.json
package.json
src/App.tsx
src/components/InterviewView.tsx
src/components/admin/AdminRoute.tsx
src/components/admin/TechnicalQuestionCreateEdit.tsx
src/components/admin/TechnicalQuestionList.tsx
src/hooks/useAuth.tsx
src/pages/admin/TechnicalQuestionCreateEditPage.tsx
src/pages/admin/TechnicalQuestionsPage.tsx
src/services/member.ts
src/services/question.ts
src/types.ts

Author: Shawn
Added pages to create and edit questions.
We should probably have a way to create questions :P

Add way to create questions

---

package-lock.json
package.json
src/components/admin/TechnicalQuestionList.tsx
src/pages/JoinPage.tsx
src/services/question.ts
src/types.ts

Author: Shawn
Added markdown to question page and dropdown to view all the info from a question.

Add markdown to questions

---

src/services/member.ts
src/types.ts

I hope this fixes it i didn't test it

Fix directory

---

src/components/InterviewPreview.tsx
src/services/directory.ts
src/services/interview.ts
src/services/member.ts
src/services/question.ts

Author: Elijah Melton
Forgot some trailing slashes. Also, added caching to directory since it's read-only and gets spammed. Will probably want to either add a new endpoint to fix, but this mitigates repeated requests at the very least. Note that cache is cleared on refresh...

added caching and trailing slashes

---

package-lock.json
package.json
src/App.tsx
src/components/InterviewSignupForm.tsx
src/components/Layout.tsx
src/components/LeetcodeProfile.tsx
src/components/admin/TechnicalQuestionCard.tsx
src/components/admin/TechnicalQuestionList.tsx
src/pages/admin/APIClient.tsx
src/pages/admin/AdminDashboard.tsx
src/pages/admin/QuestionQueueDashboard.tsx
src/services/question.ts
src/types.ts

Author: Elijah
Added an admin dashboard. None of the changes are user facing so you don't have to be super careful reviewing. sorry for large PR nonetheless
merge with https://github.com/swecc-uw/swecc-server/pull/42

added admin dashboard and queue management

---

src/components/ConfirmInterviewSignupStep.tsx
src/components/InterviewPreview.tsx
src/components/InterviewSignupForm.tsx
src/components/Layout.tsx
src/components/MemberList.tsx
src/components/MemberProfile.tsx
src/components/MemberProfileEdit.tsx
src/components/MemberProfileView.tsx
src/components/ProfilePictureUpload.tsx
src/components/utils/RandomUtils.tsx
src/pages/ViewInterviewsPage.tsx
src/services/interview.ts
src/services/member.ts
src/types.ts

Author: Elijah
pre fetch interviews and added pfps (rip latency)
Merge with https://github.com/swecc-uw/swecc-server/pull/43

upload pfp and prefetch interview data

---

src/App.tsx
src/hooks/useAuth.tsx
src/pages/ResetPassword.tsx
src/services/member.ts
vite.config.ts

Author: Shawn
Added a shitty password reset form, will style it later just need to allow people to update passswords.

Passwordreset

---

src/App.tsx
src/components/TechnicalQuestionCard.tsx
src/components/admin/TechnicalQuestionCard.tsx
src/components/admin/TechnicalQuestionList.tsx
src/pages/ViewInterviewPage.tsx
src/pages/admin/APIClient.tsx
src/pages/admin/PairingDashboard.tsx
src/pages/admin/QuestionQueueDashboard.tsx
src/pages/admin/TechnicalQuestionCreateEditPage.tsx
src/pages/admin/TechnicalQuestionsPage.tsx

fixed show detail

---

src/components/MemberProfileEdit.tsx

Author: Elijah
the toggle logic was backwards for isPrivate

fixed toggle for social field

---

src/hooks/useAuth.tsx

Fixed the auth message to be /verify instead of /auth v2

---

src/components/ReportPopUp.tsx
src/pages/ViewInterviewPage.tsx
src/services/member.ts
src/services/report.ts
src/types.ts

Author: Shawn
Addressed comments from PR #53 that were marked resolved but weren't resolved.
To keep the code clean

Address comments from PR 53

---

src/pages/admin/ReportDashboard.tsx

Author: Shawn
Didn't realize anchors were used, we aren't using anchors.

Fix links in report admin page.

---

src/components/MemberList.tsx
src/components/MemberProfile.tsx
src/components/MemberProfileView.tsx

fix pfp and date issue

---

src/components/InterviewSignupForm.tsx
src/components/MemberProfile.tsx
src/components/MemberProfileEdit.tsx
src/components/MemberProfileView.tsx
src/components/TimeRangeSelector/ChakaraTimeRangeSelector.tsx
src/components/TimeRangeSelector/MobileTimeRangeSelector.tsx
src/components/TimeRangeSelector/TimeRangeSelector.tsx
src/components/TimeRangeSelector/cursed-time.ts
src/localization.ts
src/pages/MemberProfilePage.tsx
src/pages/ViewInterviewsPage.tsx
src/pages/admin/QuestionQueueDashboard.tsx
src/pages/admin/ReportDashboard.tsx
src/services/admin/AdminCommandRpc.ts
src/services/interview.ts
src/services/member.ts
src/services/question.ts
src/services/report.ts
src/types.ts

Author: Elijah
overhaul date handling
it was pissing me off
@ShawnCollinge please look at date handling when you get a chance, I'm not an expert on this stuff so there's probably a better way to do it

fix dates  everywhere

---

package-lock.json
package.json
src/components/MemberList.tsx
src/hooks/useDelay.tsx
src/pages/DirectoryPage.tsx
src/services/directory.ts

Merge only after 
- https://github.com/swecc-uw/swecc-client/pull/76 (plus rebase)
- https://github.com/swecc-uw/swecc-server/pull/59
---
Author: Elijah 
made searching better

Search pag

---

src/components/MemberProfileEdit.tsx

Author: Elijah
Fixed bugs in linked issues
bug
N/A

Fix issues in social field profile editing

---

src/components/MemberProfileView.tsx
src/components/ReportPopUp.tsx
src/components/TechnicalQuestionCard.tsx
src/pages/ViewInterviewPage.tsx
src/pages/admin/AdminConsolePage.tsx
src/pages/admin/ReportDashboard.tsx
src/services/interview.ts
src/services/report.ts
src/types.ts

Author: Elijah
Can now report from a person's profile, a question, or interview itself
Merge with https://github.com/swecc-uw/swecc-server/pull/61

reporting everywhere

---

src/components/admin/TechnicalQuestionCreateEdit.tsx
src/services/question.ts
src/types.ts

Author: Elijah
Include topic id for real
Wasn't letting me create a question
NO

send topic_id

---

src/components/DiscordVerification.tsx
src/hooks/useAuth.tsx
src/pages/AuthPage.tsx

Author: Elijah
Very specific about what username to use, and also automatically try to log in w/ provided user/pw after registration to bring user to verification component

Better instructions for verification

---

package-lock.json
package.json

Author: Elijah
rename this component to `swecc-interview`
seems more consistent

Rename client to interview

---

src/components/admin/ReportObjectView.tsx
src/components/admin/ReportStatusView.tsx
src/components/admin/ReportTypeView.tsx
src/components/admin/ReportView.tsx
src/components/admin/ReportedInterview.tsx
src/components/admin/ReportedMember.tsx
src/components/admin/ReportedQuestion.tsx
src/pages/admin/ReportDashboard.tsx
src/services/report.ts
src/types.ts

Author: Advay
See title. Note: the functionality regarding closing and modifying issues has not been implemented, this PR only improves the UI of the report dashboard.

Upgrades to Report UI

---

src/components/admin/ReportView.tsx
src/hooks/admin/useAdmins.tsx
src/services/member.ts
src/services/report.ts
src/types.ts

Author: Advay
Add functionality for assigning admins to reports.
Improve moderation

Admin assignments

---

src/components/MemberList.tsx
src/components/MemberProfileEdit.tsx
src/components/MemberProfileView.tsx

Author: Elijah
Add preview and resumeUrl fields to profile view and edit, and improved search result view

Update profile view

---

src/components/InterviewSignupForm.tsx

Author: Advay
See title.
Better UI.

Replace carousel with modal for interview confirmation

---

src/components/utils/CopyableText.tsx
src/pages/ViewInterviewPage.tsx

Author: Elijah
- Link to user's profile in interview page
- Add email and discord with copyable text
- Remove duplicate flag icon on report interview

link to profile, added email and discord

---

.gitignore
package-lock.json
src/components/utils/CopyableText.tsx
src/pages/admin/PairingDashboard.tsx
src/services/interview.ts
src/services/report.ts
src/types.ts

Author: Justin
Added ui toggle to display current week + previous week's pairings
To allow for automated scripts to run pairings
Old:

See swecc-server #110

---

src/components/Layout.tsx

fix redirect issue

---

src/components/DiscordVerification.tsx
src/pages/AuthPage.tsx
src/services/member.ts

Add UI for changing discord username from verification modal

---

package-lock.json
src/components/GithubProfile.tsx
src/components/LeetcodeProfile.tsx
src/pages/MemberProfilePage.tsx
src/services/engagement.ts
src/types.ts

Author: Elijah
Called our APIs instead for leetcode and discord stats
Annoying latency
(ignore that it is shawn's lc profile, just needed while leaderboard testing)

update activity overview
